In [1]:
import requests
import pandas as pd
url="https://fakestoreapi.com/products"
responces = requests.get(url)
data = responces.json()
df = pd.DataFrame(data)
df.head(3)

,id,title,price,description,category,image,rating
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,"{'rate': 3.9, 'count': 120}"
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,"{'rate': 4.1, 'count': 259}"
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,"{'rate': 4.7, 'count': 500}"

In [2]:
df.info

<bound method DataFrame.info of     id                                              title   price  \
0    1  Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...  109.95
1    2             Mens Casual Premium Slim Fit T-Shirts    22.30
2    3                                 Mens Cotton Jacket   55.99
3    4                               Mens Casual Slim Fit   15.99
4    5  John Hardy Women's Legends Naga Gold & Silver ...  695.00
5    6                       Solid Gold Petite Micropave   168.00
6    7                         White Gold Plated Princess    9.99
7    8  Pierced Owl Rose Gold Plated Stainless Steel D...   10.99
8    9  WD 2TB Elements Portable External Hard Drive -...   64.00
9   10  SanDisk SSD PLUS 1TB Internal SSD - SATA III 6...  109.00
10  11  Silicon Power 256GB SSD 3D NAND A55 SLC Cache ...  109.00
11  12  WD 4TB Gaming Drive Works with Playstation 4 P...  114.00
12  13  Acer SB220Q bi 21.5 inches Full HD (1920 x 108...  599.00
13  14  Samsung 49-Inch CHG90 144Hz Curved Gaming Moni...  999.99
14  15  BIYLACLESEN Women's 3-in-1 Snowboard Jacket Wi...   56.99
15  16  Lock and Love Women's Removable Hooded Faux Le...   29.95
16  17  Rain Jacket Women Windbreaker Striped Climbing...   39.99
17  18        MBJ Women's Solid Short Sleeve Boat Neck V     9.85
18  19                 Opna Women's Short Sleeve Moisture    7.95
19  20         DANVOUY Womens T Shirt Casual Cotton Short   12.99

                                          description          category  \
0   Your perfect pack for everyday use and walks i...    men's clothing
1   Slim-fitting style, contrast raglan long sleev...    men's clothing
2   great outerwear jackets for Spring/Autumn/Wint...    men's clothing
3   The color could be slightly different between ...    men's clothing
4   From our Legends Collection, the Naga was insp...          jewelery
5   Satisfaction Guaranteed. Return or exchange an...          jewelery
6   Classic Created Wedding Engagement Solitaire D...          jewelery
7   Rose Gold Plated Double Flared Tunnel Plug Ear...          jewelery
8   USB 3.0 and USB 2.0 Compatibility Fast data tr...       electronics
9   Easy upgrade for faster boot up, shutdown, app...       electronics
10  3D NAND flash are applied to deliver high tran...       electronics
11  Expand your PS4 gaming experience, Play anywhe...       electronics
12  21. 5 inches Full HD (1920 x 1080) widescreen ...       electronics
13  49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MON...       electronics
14  Note:The Jackets is US standard size, Please c...  women's clothing
15  100% POLYURETHANE(shell) 100% POLYESTER(lining...  women's clothing
16  Lightweight perfet for trip or casual wear---L...  women's clothing
17  95% RAYON 5% SPANDEX, Made in USA or Imported,...  women's clothing
18  100% Polyester, Machine wash, 100% cationic po...  women's clothing
19  95%Cotton,5%Spandex, Features: Casual, Short S...  women's clothing

                                                image  \
0   https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...
1   https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...
2   https://fakestoreapi.com/img/71li-ujtlUL._AC_U...
3   https://fakestoreapi.com/img/71YXzeOuslL._AC_U...
4   https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...
5   https://fakestoreapi.com/img/61sbMiUnoGL._AC_U...
6   https://fakestoreapi.com/img/71YAIFU48IL._AC_U...
7   https://fakestoreapi.com/img/51UDEzMJVpL._AC_U...
8   https://fakestoreapi.com/img/61IBBVJvSDL._AC_S...
9   https://fakestoreapi.com/img/61U7T1koQqL._AC_S...
10  https://fakestoreapi.com/img/71kWymZ+c+L._AC_S...
11  https://fakestoreapi.com/img/61mtL65D4cL._AC_S...
12  https://fakestoreapi.com/img/81QpkIctqPL._AC_S...
13  https://fakestoreapi.com/img/81Zt42ioCgL._AC_S...
14  https://fakestoreapi.com/img/51Y5NI-I5jL._AC_U...
15  https://fakestoreapi.com/img/81XH0e8fefL._AC_U...
16  https://fakestoreapi.com/img/71HblAHs5xL._AC_U...
17  https://fakestoreapi.com/img/71z3kpMAYsL._AC_U...
18  https://fakestoreapi.com/img/51eg55uWmdL._AC_U...
19  https://fakestoreapi.com/img/61pHAEJ4NML._AC_U...

                         rating
0   {'rate': 3.9, 'count': 120}
1   {'rate': 4.1, 'count': 259}
2   {'rate': 4.7, 'count': 500}
3   {'rate': 2.1, 'count': 430}
4   {'rate': 4.6, 'count': 400}
5    {'rate': 3.9, 'count': 70}
6     {'rate': 3, 'count': 400}
7   {'rate': 1.9, 'count': 100}
8   {'rate': 3.3, 'count': 203}
9   {'rate': 2.9, 'count': 470}
10  {'rate': 4.8, 'count': 319}
11  {'rate': 4.8, 'count': 400}
12  {'rate': 2.9, 'count': 250}
13  {'rate': 2.2, 'count': 140}
14  {'rate': 2.6, 'count': 235}
15  {'rate': 2.9, 'count': 340}
16  {'rate': 3.8, 'count': 679}
17  {'rate': 4.7, 'count': 130}
18  {'rate': 4.5, 'count': 146}
19  {'rate': 3.6, 'count': 145}  >

In [3]:
df.shape

(20, 7)

In [4]:
df.description

0     Your perfect pack for everyday use and walks i...
1     Slim-fitting style, contrast raglan long sleev...
2     great outerwear jackets for Spring/Autumn/Wint...
3     The color could be slightly different between ...
4     From our Legends Collection, the Naga was insp...
5     Satisfaction Guaranteed. Return or exchange an...
6     Classic Created Wedding Engagement Solitaire D...
7     Rose Gold Plated Double Flared Tunnel Plug Ear...
8     USB 3.0 and USB 2.0 Compatibility Fast data tr...
9     Easy upgrade for faster boot up, shutdown, app...
10    3D NAND flash are applied to deliver high tran...
11    Expand your PS4 gaming experience, Play anywhe...
12    21. 5 inches Full HD (1920 x 1080) widescreen ...
13    49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MON...
14    Note:The Jackets is US standard size, Please c...
15    100% POLYURETHANE(shell) 100% POLYESTER(lining...
16    Lightweight perfet for trip or casual wear---L...
17    95% RAYON 5% SPANDEX, Made in USA or Imported,...
18    100% Polyester, Machine wash, 100% cationic po...
19    95%Cotton,5%Spandex, Features: Casual, Short S...
Name: description, dtype: str

In [5]:
df['rating_rate']=df['rating'].apply(lambda x:x['rate'])
df['rating_count']=df['rating'].apply(lambda x:x['count'])
df=df.drop(columns=['rating'])
df.head()

,id,title,price,description,category,image,rating_rate,rating_count
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,3.9,120
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,4.1,259
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,4.7,500
3,4,Mens Casual Slim Fit,15.99,The color could be slightly different between ...,men's clothing,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,2.1,430
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,"From our Legends Collection, the Naga was insp...",jewelery,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,4.6,400

In [6]:
def to_camel_case(col):
    parts = col.split(" ")
    return parts[0]+' '.join(word.capitalize() for word in parts[1:])
df.columns=[to_camel_case(col) for col in df.columns]
print(df.columns)

Index(['id', 'title', 'price', 'description', 'category', 'image',
       'rating_rate', 'rating_count'],
      dtype='str')

In [7]:
df['price']=df['price'].round(0)
df['price']=df['price'].astype(int)

In [8]:
df['title']=df['title'].str.strip()
df['category']=df['category'].str.lower().str.strip()
df['description']=df['description'].str.strip()

In [9]:
df['category'] = df['category'].replace({
    "men's clothing": "men",
    "women's clothing": "women",
    "jewelery": "jewelry"
})

In [10]:
def price_category(price):
    if price <50:
        return "Low"
    elif price <150:
        return "medium"
    else:
        return "High"
    
df["price_Category"]=df["price"].apply(price_category)

In [11]:
df.head()

,id,title,price,description,category,image,rating_rate,rating_count,price_Category
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",110,Your perfect pack for everyday use and walks i...,men,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,3.9,120,medium
1,2,Mens Casual Premium Slim Fit T-Shirts,22,"Slim-fitting style, contrast raglan long sleev...",men,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,4.1,259,Low
2,3,Mens Cotton Jacket,56,great outerwear jackets for Spring/Autumn/Wint...,men,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,4.7,500,medium
3,4,Mens Casual Slim Fit,16,The color could be slightly different between ...,men,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,2.1,430,Low
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695,"From our Legends Collection, the Naga was insp...",jewelry,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,4.6,400,High

In [12]:
df['titleLength'] = df['title'].apply(len)

In [13]:
df['Popularity_Score']=df["rating_rate"]*df["rating_count"]

In [14]:
df=df.sort_values(by='rating_rate',ascending=False)

In [20]:
df.head(3)

,id,title,price,description,category,image,rating_rate,rating_count,price_Category,titleLength,Popularity_Score
11,12,WD 4TB Gaming Drive Works with Playstation 4 P...,114,"Expand your PS4 gaming experience, Play anywhe...",electronics,https://fakestoreapi.com/img/61mtL65D4cL._AC_S...,4.8,400,medium,73,1920.0
10,11,Silicon Power 256GB SSD 3D NAND A55 SLC Cache ...,109,3D NAND flash are applied to deliver high tran...,electronics,https://fakestoreapi.com/img/71kWymZ+c+L._AC_S...,4.8,319,medium,76,1531.2
2,3,Mens Cotton Jacket,56,great outerwear jackets for Spring/Autumn/Wint...,men,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,4.7,500,medium,18,2350.0

In [15]:
print(df.groupby('category')['price'].mean())

category
electronics    332.500000
jewelry        221.000000
men             51.000000
women           26.333333
Name: price, dtype: float64

In [16]:
print(df.groupby('price_Category')['id'].count())

price_Category
High      4
Low       9
medium    7
Name: id, dtype: int64

In [17]:
df.to_csv("cleaned_products.csv", index=False)

In [18]:
import pyodbc

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=Localhost\SQLDEV;"   # change this
    "DATABASE=ecommerce_db;"
    "Trusted_Connection=yes;"
)

cursor = conn.cursor()

print("✅ Connected to SQL Server!")

✅ Connected to SQL Server!

<>:5: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
<>:5: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
C:\Users\sumit\AppData\Local\Temp\ipykernel_31392\3742323109.py:5: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
  "SERVER=Localhost\SQLDEV;"   # change this

In [21]:
for _, row in df.iterrows():
    cursor.execute("""
        INSERT INTO products (
            id, title, price, category, description, image,
            rating_rate, rating_count,
            price_Category, Popularity_Score, titleLength
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        row['id'],
        row['title'],
        row['price'],
        row['category'],
        row['description'],
        row['image'],
        row['rating_rate'],
        row['rating_count'],
        row['price_Category'],
        row['Popularity_Score'],
        row['titleLength']
    ))

conn.commit()
print("✅ Data inserted successfully!")

✅ Data inserted successfully!